version: "3"
services:
  auth:
    build: ./auth
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./auth:/app
    links:
      - auth_mongo
    environment:
      USERNAME: nikola
      PASSWORD: bodrozic
  auth_mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: nikola
      MONGO_INITDB_ROOT_PASSWORD: bodrozic
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
